"""Build a scoped report from checked case receipts, retaining coverage gaps."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parent;E=ROOT/'evidence'
def read(name):return json.loads((E/name).read_text())
cases=read('case_analysis.json');live=read('live_oracle_summary.json');faults=read('fault_summary.json')
assert len(cases)==18 and len(live)==2 and len(faults)==6,(len(cases),len(live),len(faults))
lines=['# Qwen3-1.7B eight-GPU implementation validation','',
'Production source: `37a812d41ec7c1c5a070ee7741bed819f60aed55`; oracle: `d23da0e17830c296ae6e375793a7ccea98870bb3`; disabled baseline: `bfa08860fee9f4febaf7aa1041f0e7eb0ac09cd5`. Model: `/workspace/models/Qwen3-1.7B-Base`. Eight UUID-bound A100-SXM4-40GB GPUs, eight-rank FSDP and eight TP=1 rollout replicas. Full resolved configuration and exact commands are in each case directory. Model/tokenizer/config/data hashes and dependency versions: `manifest.json`, with live revalidation receipts. Frozen prompt manifest: `prompts.jsonl` / `prompts.parquet`.', '',
'## Verdict and limits','',
'The completed gates below verify this model/configuration only. DAPO exhaustion leaves update coverage incomplete. Frozen cap-hit transitions were 24 smoke and 9 full, all 0→0. No natural nonzero task-score correction was observed; missing correctness transitions remain uncovered in real verifier evidence and are covered only by existing deterministic tests. Independent rollout tokens can differ; exact equivalence claims apply to frozen inputs/outputs. No training-effectiveness, capacity or performance improvement claim is made.', '',
'## Environment, replay and actor gates','',
'- PASS: fresh per-device CUDA arithmetic, eight-rank NCCL sum 36 and UUID mapping; 190 CPU tests plus both byte-exact frozen characterizations (`cpu_release_retry/`).',
'- PASS: H128/L512 real capture (8 prompts / 32 rows / 24 cap hits), H2048/L8192 capture (32 prompts / 128 rows / 9 cap hits). Raw token IDs, finish metadata and unchanged math_dapo verifier outputs retained.',
'- PASS: frozen original runtime/adapter versus hook, off/shadow/replace request/mask/score/order equality (`replay_h128_v3/`, `replay_h2048_v3/`). Smoke independent repeats differ; full repeats happened to match in this sample.',
'- PASS: actual eight-rank FSDP registered vanilla/GSPO losses and backward. H128 uses 32 rows; H2048 uses first 2 prompts / 8 rows. Repeated full loss inputs and gradient shards, and cross-mode results, compare exactly (`actor_h128/`, `actor_h2048/`, `actor_cross_mode.json`).',
'- PASS: GPU GSPO masked-tail isolation; original GRPO recomputation with controlled score change changes gradient. The score change is synthetic, separately labeled (`tail_isolation.json`).',
'- PASS: reference forward at KL coefficient zero; eight workers have exact input IDs/positions/masks and prefix logprobs of shape [8,2048], initial old/ref equality (`reference_alignment.json`).','',
'## Trainer and diagnostic cases','',
'Optimizer steps count actual AdamW calls across all eight ranks. Changed shards count receipts with different before/after checksums. Version columns distinguish publication completion and actual normal rollout metadata. Two-step cases publish version 1 before step two and version 2 at completion. Serving the nonzero step-two update (version 2) is UNCOVERED in standard cases; only versions 0/1 were actually used by normal rollouts. DAPO replace separately covers actual serving after a nonzero update.', '',
'| Case | Status | Steps | Changed shard receipts | Published | Served normal | Seconds |',
'|---|---|---:|---:|---|---|---:|']
for r in cases:
 lines.append(f"| {r['case']} | {r['status']} | {r['logical_optimizer_steps']} | {r['weight_changed_receipts']} | {r['published_versions']} | {r['observed_normal_versions']} | {r['seconds']:.1f} |")
lines += ['', 'Standard main cases have two optimizer calls; the first has zero gradients, and the second changes all eight shards. DAPO off/shadow exhaust four candidate rounds without update; DAPO replace changes all eight shards once, serves version 1, then exhausts the next candidate budget. Data, reward and filtering were not adjusted.', '', '## Live oracle and fault barriers','']
for r in live:lines.append(f"- {r['status']}: live {r['horizon']}, {r['request_count']} requests, exact requests/masks and frozen adapter scores, {len(r['independent_tail_differences'])} independent tail differences, zero optimizer updates. Controlled pre-update exit is expected.")
for r in faults:lines.append(f"- {r['status']}: injected {r['fault']}, {r['injections']} injection receipts, {r['optimizer_receipts']} optimizer receipts, published versions {r['published_versions']}.")
lines += ['', 'Faults are controlled callback/service-boundary injections, including a synthetic TimeoutError, not induced wall-clock network outages. Unconfirmed release requires no later sleep attempt. Expected nonzero exits are PASS only when the suite verifies injection/completion receipts and update barriers; timeout never passes.', '', '## Evidence and resources','',
'`case_analysis.json` records exact actor short-prefix identity, finite loss/gradient metrics, actual UUIDs, continuation/release counts and reward chunk padding. Standard enabled cases exercise real 3-row reward chunks padded to 4 across two workers. Engine/worker import receipts exist for every main case; expanded server/reward module and remote release/drain acknowledgement instrumentation was added for later live/fault diagnostics. Earlier main cases retain runtime cleanup intervals rather than separate remote acknowledgement files. Worker audit files retain raw reward and actor batches, gradients, weight hashes, publication receipts, import paths, release/drain evidence and profiling intervals. Raw scores remain saved separately; corrections are restricted to the last valid H token; no continuation tail enters the actor.', '']
for h in [128,2048]:
 p=read(f'h{h}_processes.json');ranks=[read(f'actor_h{h}/rank{r}.json') for r in range(8)]
 lines.append(f"- H{h} direct capture: {p['seconds']:.1f} s, sampled NVML peak per GPU {p['peak_sampled_mib']} MiB. Actor replay maximum CUDA allocated: {max(r['peak_allocated'] for r in ranks)/2**30:.3f} GiB.")
lines += ['', 'Trainer per-case wall time is listed above; CUDA allocation/reservation metrics are retained in `case_analysis.json`. NVML samples, CUDA allocation counters and profiling intervals measure different scopes and are not equated. Audit I/O overhead is included; timing equality is not asserted.', '', '## Isolation, corrections and reproduction','',
'No production algorithm/source fix was needed. Private runner fixes handle vLLM UUID parsing with a lazy import shim, Ray device assignment, private short IPC paths, CPU placement capacity and typed seed configuration. Earlier failed attempts and original logs remain in evidence. The final release-fault launch was first blocked by a transient GPU0 process-occupancy snapshot before trainer startup; its directory is retained with `_gate_attempt1`. The launcher now requires two idle snapshots with an empty compute-process list, and the release case was retried only after a fresh gate. No golden/detector/loss mathematics or shared dependencies changed. No formal checkpoint or benchmark evaluation ran.', '',
'Reproduction commands and fixed parameters: `../README.md`. Each trainer directory includes `config.yaml`, `process.json`, gate and runtime logs. Final cleanup and provenance receipts: `final_state.json`, `final_manifest.json`. Final inspection found no owned processes and all eight GPUs at 0 MiB / 0% utilization; no forced process termination was needed. Validation code is committed separately from raw evidence/cache files.']
(E/'REPORT.md').write_text('\n'.join(lines)+'\n')
files={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in ROOT.rglob('*.py') if 'evidence' not in p.parts and not any('cache' in x for x in p.parts) and 'compat_v3' not in p.parts}
(E/'runner_sha256.json').write_text(json.dumps(files,indent=2))
print(E/'REPORT.md')
